class AppointmentFields:
    ID = 'Appointments ID'
    START_DATE_TIME = 'Appointments Start Date Time'
    END_DATE_TIME = 'Appointments End Date Time'
    MEDIUM = 'Appointment Medium Name'
    TYPE_LENGTH = 'Appointment Type Length (Minutes)'
    TYPE = 'Appointment Types Name'
    STATUS = 'Appointments Status'
    STAFF_MEMBER_EMAIL = 'Staff Member Email'
    STAFF_MEMBER_FIRST_NAME = 'Staff Member First Name'
    STAFF_MEMBER_LAST_NAME = 'Staff Member Last Name'
    STUDENT_USERNAME = 'Student Username'
    STUDENT_ID = 'Student ID'
    STUDENT_SCHOOL_YEAR = 'Student School Year (at Appt. Time) Name'
    STUDENT_MAJORS = 'Student Majors (at Appt. Time) Name'
    STUDENT_COLLEGE_ID = 'Student College (at Appt. Time) ID'
    STUDENT_LABELS_LIST = 'Student Institution Labels Name List'
    IS_DROP_IN = 'Appointments Drop-in? (Yes / No)'


class EventFields:
    ID = 'Events ID'
    START_DATE_TIME = 'Events Start Date Time'
    NAME = 'Events Name'
    STUDENT_ID = 'Student Attendees ID'
    IS_PRE_REGISTERED = 'Attendees Pre-Registered? (Yes / No)'
    LABEL = 'Institution Labels Name'
    CAREER_CENTER = 'Career Center Name'
    EVENT_TYPE = 'Event Type Name'
    LABELS_LIST = 'Institution Labels Name List'
    IS_INVITE_ONLY = 'Events Invite Only? (Yes / No)'
